name: Pull Bing Image

on:
#  schedule:
#    - cron: '0 0 * * *'  # 每天凌晨执行
  push:
    branches: [ main ]
jobs:
  pull-bing-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Bing Image
        run: |
          URL="https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US"
          IMAGE_PATH="$(curl -s $URL | jq -r '.images[0].url' | sed 's/^/https:\/\/www.bing.com/;s/1366x768.jpg$/1920x1080.jpg/')"
          #FILE_NAME="$(echo $IMAGE_PATH | awk -F '/' '{print $NF}')"
          FILE_NAME="$(date +"%Y%m%d").jpg"
          mkdir -p images
          curl -s $IMAGE_PATH -o "images/$FILE_NAME"
          #复制文件
          cp images/$FILE_NAME images/lastest.jpg

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: commit, push
        uses: EndBug/add-and-commit@v9
        with:
          add: "-A"
          author_name: ${{ secrets.NAME }}
          author_email: ${{ secrets.EMAIL }}
          message: "Update wallpaper bing image"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}